name: PSP Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  psp:
    name: Build (PSP)
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          apk update
          apk add cmake

      - name: Configure project
        run: |
          cmake -S . \
                -B build \
                -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake \
                -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -D CELESTE_P8_ENABLE_AUDIO=ON

      - name: Build project
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: PSP_build
          path: |
            build/EBOOT.PBP 
            build/PARAM.SFO 
            export/data
          if-no-files-found: error
